Repository ziomciopoziomcio/ProgramoGranie_server, pull requests merged in 2025-06, with the labels that each got.

#61 Challange page code structure changes
  server.py
  static/js/challenge.js
  templates/challenge_page.html
Labels: wontfix

#65 Changed backend for admin_page
  server.py
Labels: enhancement

#67 41 add backend to game page items
  static/assets/game_assets/fb_bg_hell_1.png
  static/assets/game_assets/fb_bg_hell_1_preview.png
  static/assets/game_assets/fb_bg_hell_2.png
  static/assets/game_assets/fb_bg_hell_2_preview.png
  static/assets/game_assets/fb_bg_regular_2.png
  static/assets/game_assets/fb_bg_regular_2_preview.png
  static/assets/game_assets/fb_pipe_red.png
  static/assets/game_assets/fb_skin_dantebird.png
  static/game.js
  static/js/game.js
  templates/game_page.html
Labels: fix

#69 Add dynamic content for challenges
  server.py
  static/css/challenge_style.css
  templates/challenge_page.html
  templates/main_menu_page.html
Labels: fix

#70 Make main page content dynamic
  server.py
  static/assets/stats_assets/medal_so2_bronze.png
  static/assets/stats_assets/medal_so2_gold.png
  static/css/main_page_style.css
  static/css/profile_style.css
  templates/main_menu_page.html
  templates/profile_page.html
Labels: wontfix

#73 Copy of dynamic content from challenge page to game page
  server.py
  static/js/challenge.js
  templates/challenge_page.html
  templates/game_page.html
Labels: enhancement, fix

#72 Stats pages content fix
  static/css/main_page_style.css
  static/css/stats_style.css
  templates/main_menu_page.html
  templates/pp1_stats_page.html
  templates/pp2_stats_page.html
  templates/so2_stats_page.html
Labels: wontfix

#79 Add audio
  static/assets/game_assets/audio/przegrana.mp3
  static/assets/game_assets/audio/skok.mp3
  static/assets/game_assets/audio/soundtrack_flappy_dante.mp3
  static/game.js
Labels: enhancement

#82 Quick fix
  templates/admin_panel.html
  templates/game_page.html
Labels: fix
