Repository ziomciopoziomcio/ProgramoGranie_server, pull requests merged in 2025-05, with the labels that each got.

#7 Project form standardization
  server.py
  static/assets/achievement_placeholder.png
  static/assets/dante_coin.png
  static/assets/dante_main_logo.png
  static/assets/fb_bg_1.png
  static/assets/fb_logo.png
  static/assets/fire_1.png
  static/assets/logo_main_1.0.png
  static/assets/medal_empty.png
  static/assets/play_button.png
  static/assets/profile_photo.svg
  static/assets/profile_photo_white.svg
  static/assets/skin_locked.png
  static/css/style.css
  templates/challenge_page.html
  templates/flappy_bird.html
  templates/game/assets/fb_bg_1.png
  templates/game/assets/fb_heart_empty.png
  templates/game/assets/fb_heart_full.png
  templates/game/assets/fb_logo.png
  templates/game/assets/fb_pipe_green.png
  templates/game/assets/fb_play_button.png
  templates/game/assets/fb_skin_default.png
  templates/game/flappy_bird.html
  templates/game/flappy_bird.py
  templates/game/static/game.js
  templates/game_page.html
  templates/login_page.html
  templates/main_menu_page.html
  templates/pp1_stats_page.html
  templates/pp2_stats_page.html
  templates/profile_page.html
  templates/so2_stats_page.html
Labels: enhancement

#12 Change statistics page routes to /so2, /pp1, /pp2 and update breadcrumb
  server.py
Labels: bug

#22 Enable real authentication on login page
  .gitignore
  server.py
  static/css/style.css
  templates/login_page.html
Labels: enhancement

#18 Flappy bird is currently working
  static/game.js
Labels: fix

#20 File upload currently working
  .gitignore
  server.py
  static/js/challenge.js
  templates/challenge_page.html
Labels: enhancement

#23 Added functionality to info buttons on main page
  static/css/style.css
  static/js/main_menu.js
  templates/main_menu_page.html
Labels: enhancement

#24 Media queries
  static/css/style.css
  templates/main_menu_page.html
  templates/pp1_stats_page.html
  templates/pp2_stats_page.html
  templates/so2_stats_page.html
Labels: bug

#26 Clicking the play button navigates to the game page
  static/js/challenge.js
  templates/challenge_page.html
Labels: enhancement

#27 Add navigation to challenge page
  static/css/style.css
  static/js/main_menu.js
  templates/main_menu_page.html
Labels: enhancement

#35 added assets
  static/assets/stats_assets/ach_alokator_bronze.png
  static/assets/stats_assets/ach_alokator_gold.png
  static/assets/stats_assets/ach_alokator_silver.png
  static/assets/stats_assets/ach_fat_bronze.png
  static/assets/stats_assets/ach_fat_gold.png
  static/assets/stats_assets/ach_fat_silver.png
  static/assets/stats_assets/ach_igrzyska_bronze.png
  static/assets/stats_assets/ach_igrzyska_gold.png
  static/assets/stats_assets/ach_igrzyska_silver.png
  static/assets/stats_assets/ach_pp1_bronze.png
  static/assets/stats_assets/ach_pp1_gold.png
  static/assets/stats_assets/ach_pp1_silver.png
  static/assets/stats_assets/ach_pp2_bronze.png
  static/assets/stats_assets/ach_pp2_gold.png
  static/assets/stats_assets/ach_pp2_silver.png
  static/assets/stats_assets/ach_so2_bronze.png
  static/assets/stats_assets/ach_so2_gold.png
  static/assets/stats_assets/ach_so2_silver.png
  static/assets/stats_assets/ach_win_igrzyska.png
  static/assets/stats_assets/medal_pp1_bronze.png
  static/assets/stats_assets/medal_pp1_gold.png
  static/assets/stats_assets/medal_pp1_silver.png
  static/assets/stats_assets/medal_pp2_bronze.png
  static/assets/stats_assets/medal_pp2_gold.png
  static/assets/stats_assets/medal_pp2_silver.png
  static/assets/stats_assets/medal_so2_br.png
  static/assets/stats_assets/medal_so2_gld.png
  static/assets/stats_assets/medal_so2_silver.png
Labels: enhancement

#37 Admin panel created
  server.py
  static/css/admin_style.css
  templates/admin_panel.html
Labels: enhancement

#42 Flappy bird design and more
  static/assets/game_assets/fb_heart_empty.png
  static/assets/game_assets/fb_heart_full.png
  static/assets/game_assets/fb_pipe_green.png
  static/assets/game_assets/fb_skin_default.png
  static/css/challenge_style.css
  static/game.js
  templates/game/flappy_bird.html
  templates/game_page.html
Labels: enhancement, fix

#39 created register page
  server.py
  static/css/login_style.css
  static/css/register_style.css
  static/js/register.js
  templates/login_page.html
  templates/register_page.html
Labels: enhancement

#44 Added heart life tracking to the the game
  static/game.js
  templates/game/flappy_bird.html
Labels: enhancement

#49 31 connecting achievements to db
  config/data_generators/ach_generator.py
  server.py
  templates/profile_page.html
Labels: enhancement

#47 Connecting stats page to db
  config/data_generators/pp1_stats.py
  config/data_generators/pp2_stats.py
  config/data_generators/so2_stats.py
  server.py
  static/css/stats_style.css
  templates/pp1_stats_page.html
  templates/pp2_stats_page.html
  templates/so2_stats_page.html
Labels: enhancement
